name: flutzy
description: Yatzy-based dice game.

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sliding_up_panel: ^1.0.1
  material_design_icons_flutter: ^4.0.5045
  provider: ^4.0.4
  audioplayers: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4


flutter:
  uses-material-design: true

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/RobotoCondensed-Regular.ttf
  assets:
    - assets/


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "icons/icon.png"
  adaptive_icon_background: "icons/icon_bg.png"
  adaptive_icon_foreground: "icons/icon_fg.png"
